// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZVjGVXlhSSIUajMerRo0C17DUWM9LH_A',
    appId: '1:813229464460:web:948b8de01942778102d4a9',
    messagingSenderId: '813229464460',
    projectId: 'rtpsilveryalgud-33042',
    authDomain: 'rtpsilveryalgud-33042.firebaseapp.com',
    storageBucket: 'rtpsilveryalgud-33042.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZVjGVXlhSSIUajMerRo0C17DUWM9LH_A',
    appId: '1:813229464460:web:8d8e74bcc645664902d4a9',
    messagingSenderId: '813229464460',
    projectId: 'rtpsilveryalgud-33042',
    authDomain: 'rtpsilveryalgud-33042.firebaseapp.com',
    storageBucket: 'rtpsilveryalgud-33042.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3w788w-hjccggnjzALDvOUApc1mEUOa8',
    appId: '1:813229464460:android:4d21f8831c78daa102d4a9',
    messagingSenderId: '813229464460',
    projectId: 'rtpsilveryalgud-33042',
    storageBucket: 'rtpsilveryalgud-33042.appspot.com',
  );

}